# name: Infrastructure Tests

# on: push

# jobs:
#   opentofu_test:
#     name: "Run OpenTofu tests"
#     runs-on: ubuntu-latest
#     permissions:
#       id-token: write
#       contents: read
#     steps:
#       - uses: actions/checkout@v7

#       - name: Debug GitHub context
#         run: |
#           echo "Repository: $GITHUB_REPOSITORY"
#           echo "Ref: $GITHUB_REF"
#           echo "Actor: $GITHUB_ACTOR"

#       - uses: aws-actions/configure-aws-credentials@v6
#         with:
#           # TODO: fill in your IAM role ARN!
#           role-to-assume: arn:aws:iam::866409327334:role/lambda-sample-tests
#           role-session-name: tests-${{ github.run_number }}-${{ github.actor }}
#           aws-region: eu-central-1

#       - uses: opentofu/setup-opentofu@v2

#       - name: Tofu Test
#         env:
#           TF_VAR_name: lambda-sample-${{ github.run_id }}
#         working-directory: ch5/tofu/live/lambda-sample
#         run: |
#           tofu init -backend=false -input=false
#           tofu test -verbose